import React,{useState,useEffect,useRef,createContext,useContext} from 'react';
import {categories,defaults,assetFields} from './templates';
import {request,post,cached,clearCache,date,today,nextDate,latest,status,download,csv,parseCsv} from './data';
import {Workflows} from './Workflows';
export const Context=createContext();export const useApp=()=>useContext(Context);
const glyph={circlecheck:0xe15a,addbox:0xee3c,help:0xe30b,back:0xe092,next:0xe15f,"dashboard": 57777, "objects": 57627, "buildings": 57481, "inspections": 57691, "assets": 61748, "tasks": 62505, "reports": 61358, "members": 61657, "contractors": 61474, "settings": 62318, "guide": 62268, "more": 58370, "search": 58727, "add": 57415, "close": 57706, "check": 57686, "refresh": 58644, "scan": 57842, "warning": 59084, "clock": 58710, "cloud": 57715, "edit": 61453, "delete": 57787, "download": 57857, "upload": 59029, "person": 58519, "notification": 58449, "rocket": 984413, "photo": 57416, "mail": 58308, "lock": 58289, "logout": 58291, "location": 61843, "archive": 61058, "print": 62158};
export function Icon({name}){return <span className="icon" aria-hidden="true">{String.fromCodePoint(glyph[name]||glyph.assets)}</span>;}
export function Button({children,icon,onClick,kind='',...props}){return <button className={'button '+kind} onClick={onClick} {...props}>{icon&&<Icon name={icon}/>}<span>{children}</span></button>;}
export function Tool({icon,label,onClick,...props}){return <button className="tool" aria-label={label} title={label} onClick={onClick} {...props}><Icon name={icon}/></button>;}
export function Card({children,className=''}){return <section className={'card '+className}>{children}</section>;}
export function Empty({title,description,children}){return <div className="empty"><span className="empty-icon"><Icon name="check"/></span><h3>{title}</h3><p>{description}</p>{children}</div>;}
export function Field({label,options,area,type='text',...props}){return <label className="field"><span>{label}{props.required?' *':''}</span>{options?<select {...props}><option value="">Bitte wählen</option>{options.map(o=>typeof o==='string'?<option key={o}>{o}</option>:<option key={o.id} value={o.id}>{o.name}</option>)}</select>:area?<textarea rows="3" {...props}/>:<input type={type} {...props}/>}</label>;}
export function Badge({children}){return <span className={'badge '+(String(children).match(/Geprüft|Ohne Mängel|Erledigt/)?'good':String(children).match(/Mängel|Überfällig|Hoch/)?'bad':'')}>{children}</span>;}
export function Tabs({items,value,onChange}){return <div className="tabs" role="tablist">{items.map(i=><button role="tab" aria-selected={i===value} className={i===value?'active':''} key={i} onClick={()=>onChange(i)}>{i}</button>)}</div>;}
export function Modal({title,children,onClose}){const ref=useRef();useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close();},[]);return <dialog ref={ref} onCancel={onClose}><div className="modal-title"><h2>{title}</h2><Tool icon="close" label="Schließen" onClick={onClose}/></div>{children}</dialog>;}
export function Row({icon='objects',title,subtitle,onClick,end}){return <button className="row" onClick={onClick}><span className="row-icon"><Icon name={icon}/></span><span className="row-content"><strong>{title}</strong>{subtitle&&<small>{subtitle}</small>}</span>{end||<Icon name="next"/>}</button>;}
function Auth({onLogin}) {
 const invite=new URLSearchParams(location.hash.replace(/^#/,'')),token=invite.get('invite');
 const [setup,setSetup]=useState(false),[b,S]=useState({email:invite.get('email')||'',name:'',password:'',token:token||invite.get('setup')||''}),[error,E]=useState(''),[busy,B]=useState(false);
 useEffect(()=>{request('/auth/status').then(r=>setSetup(!r.initialized)).catch(e=>E(e.message));},[]);
 const field=k=>({value:b[k],onChange:e=>S({...b,[k]:e.target.value})});
 async function submit(e){e.preventDefault();B(true);E('');try{const r=await post(token?'/auth/accept':setup?'/auth/setup':'/auth/login',b);history.replaceState(null,'',location.pathname);onLogin(r.user);}catch(e){E(e.message);}finally{B(false);}}
 return <div className="auth"><img src="/assets/logo.svg" alt="Augenblick"/><h1>Augenblick-Control</h1><p>Digitale Brandschutzprüfungen</p><Card><h2>{token?'Einladung annehmen':setup?'Arbeitsbereich einrichten':'Willkommen zurück'}</h2><form onSubmit={submit}>{(setup||token)&&<Field label="Name" required {...field('name')}/>}<Field label="E-Mail" type="email" required autoComplete="username" {...field('email')}/><Field label="Passwort" type="password" required minLength={setup||token?12:1} autoComplete={setup||token?'new-password':'current-password'} {...field('password')}/>{setup&&!token&&<Field label="Einrichtungsschlüssel" required type="password" {...field('token')}/>}<p className="error" role="alert">{error}</p><Button kind="primary full" type="submit" disabled={busy}>{busy?'Bitte warten…':setup?'Arbeitsbereich erstellen':token?'Konto aktivieren':'Anmelden'}</Button></form></Card></div>;
}
export function App(){
 const [user,U]=useState(null),[ready,R]=useState(false),[records,SR]=useState([]),[users,SU]=useState([]),[queue,SQ]=useState([]),[offline,SO]=useState(!navigator.onLine),[page,SP]=useState(location.hash.startsWith('#/')?location.hash.slice(2):'dashboard'),[modal,SM]=useState(null),[notice,SN]=useState(''),[syncing,SS]=useState(false);
 const current=useRef(records),queueRef=useRef(queue);current.current=records;queueRef.current=queue;
 const go=p=>{location.hash='/'+p;SM(null);};
 useEffect(()=>{const h=()=>{SP(location.hash.startsWith('#/')?location.hash.slice(2):'dashboard');window.scrollTo(0,0);};addEventListener('hashchange',h);request('/auth/me').then(r=>U(r.user)).catch(async e=>{if(!e.status)U(await cached('user'));}).finally(()=>R(true));return()=>removeEventListener('hashchange',h);},[]);
 async function refresh(){if(!user)return;try{const [r,u]=await Promise.all([request('/records'),request('/users')]);const q=queueRef.current;const merged=[...r.records.filter(r=>!q.some(x=>x.record.id===r.id)),...q.map(x=>x.record)];SR(merged);SU(u.users);SO(false);await cached('records:'+user.id,merged);}catch(e){if(!e.status)SO(true);else SN(e.message);}}
 useEffect(()=>{if(!user)return;cached('user',user);Promise.all([cached('records:'+user.id),cached('queue:'+user.id)]).then(([r,q])=>{if(r)SR(r);if(q){SQ(q);queueRef.current=q;}refresh();});const online=()=>{SO(false);refresh();},off=()=>SO(true);addEventListener('online',online);addEventListener('offline',off);const timer=setInterval(()=>{if(!document.hidden)refresh();},30000);return()=>{clearInterval(timer);removeEventListener('online',online);removeEventListener('offline',off);};},[user?.id]);
 async function save(kind,b){const data={...b,id:b.id||crypto.randomUUID(),_requestId:b._requestId||crypto.randomUUID()},candidate={...data,kind};let result;
  try{result=(await request('/records/'+kind,{method:'PUT',body:JSON.stringify(data)})).record;SO(false);}catch(e){if(e.status)throw e;if(kind!=='inspections')throw new Error('Offline: Stammdaten bitte nach Wiederherstellung der Verbindung speichern.');const q=[...queueRef.current.filter(x=>x.record.id!==data.id),{kind,record:candidate}];queueRef.current=q;SQ(q);await cached('queue:'+user.id,q);result={...candidate,pending:true};SO(true);}
  const next=[...current.current.filter(r=>r.id!==result.id),result];current.current=next;SR(next);await cached('records:'+user.id,next);SN(result.pending?'Prüfung offline gespeichert. Bitte später synchronisieren.':'Gespeichert');return result;
 }
 async function sync(){SS(true);try{let q=[...queueRef.current];while(q.length){const item=q[0];await request('/records/'+item.kind,{method:'PUT',body:JSON.stringify(item.record)});q=q.slice(1);queueRef.current=q;SQ(q);await cached('queue:'+user.id,q);}await refresh();SN('Alle Prüfungen synchronisiert.');}catch(e){SN(e.message+' Ausstehende Prüfungen bleiben auf diesem Gerät gespeichert.');}finally{SS(false);}}
 async function logout(){if(queue.length){SN('Bitte ausstehende Prüfungen zuerst synchronisieren.');return;}try{await post('/auth/logout',{});}catch{}await clearCache();U(null);SR([]);}
 const list=kind=>records.filter(r=>r.kind===kind&&!r.archived),find=id=>records.find(r=>r.id===id);
 const ctx={user,users,records,list,find,save,go,page,modal:SM,notify:SN,refresh,offline,queue,sync,logout};
 if(!ready)return <div className="loading">Augenblick-Control wird geladen…</div>;
 if(!user)return <Auth onLogin={U}/>;
 const nav=[['dashboard','Dashboard'],['objects','Objekte'],['inspections','Prüfungen'],['assets','Geräte'],['tasks','Aufgaben'],['reports','Berichte'],['members','Mitarbeiter'],['contractors','Subunternehmer'],['settings','Einstellungen'],['guide','Anleitung']];const active=page.split('/')[0];
 return <Context.Provider value={ctx}><div className="shell"><aside className="sidebar"><div className="brand"><img src="/assets/logo.svg" alt="Augenblick"/><div>augenblick<small>C O N T R O L</small></div></div><span className="workspace-badge">Team</span><nav>{nav.map(([id,label],i)=><React.Fragment key={id}>{[0,6,8].includes(i)&&<div className="nav-heading">{i===0?'HAUPTNAVIGATION':i===6?'TEAM':'VERWALTUNG'}</div>}<button className={active===id?'selected':''} onClick={()=>go(id)} title={label}><Icon name={id}/><span>{label}</span></button></React.Fragment>)}</nav><div className="sidebar-bottom"><Tool icon="help" label="Hilfe" onClick={()=>go('guide')}/><Tool icon="logout" label="Abmelden" onClick={logout}/></div></aside><div className="workspace"><div className="topbar"><span>{offline?'Offline':queue.length?`${queue.length} ausstehend`:''}</span><Tool icon="notification" label="Benachrichtigungen" onClick={()=>SM('notifications')}/></div>{queue.length>0&&<div className="sync-banner"><span>{queue.length} Prüfung(en) auf diesem Gerät gespeichert</span><Button onClick={sync} disabled={syncing}>Synchronisieren</Button></div>}<main><Page/></main></div><nav className="mobile-nav">{nav.slice(0,4).map(([id,label])=><button key={id} onClick={()=>go(id)} className={active===id?'selected':''}><Icon name={id}/><small>{label}</small></button>)}<button onClick={()=>SM('more')} className={!nav.slice(0,4).some(n=>n[0]===active)?'selected':''}><Icon name="more"/><small>Mehr</small></button></nav></div>{notice&&<div className="toast" role="status">{notice}<Tool icon="close" label="Meldung schließen" onClick={()=>SN('')}/></div>}{modal==='more'&&<Modal title="Mehr" onClose={()=>SM(null)}>{nav.slice(4).map(([id,label])=><Row key={id} icon={id} title={label} onClick={()=>go(id)}/>)}<Row icon="logout" title="Abmelden" onClick={logout}/></Modal>}{modal==='notifications'&&<Modal title="Benachrichtigungen" onClose={()=>SM(null)}>{list('tasks').filter(t=>t.status!=='Erledigt').map(t=><Row key={t.id} icon="tasks" title={t.title} subtitle={'Fällig: '+date(t.dueDate)} onClick={()=>go('tasks/'+t.id)}/>)}{!list('tasks').some(t=>t.status!=='Erledigt')&&<p>Keine offenen Benachrichtigungen.</p>}</Modal>}{modal==='scan'&&<Scanner onClose={()=>SM(null)}/>}</Context.Provider>;
}
export function Header({title,subtitle,back,children}){const {go}=useApp();return <header className="page-header">{back&&<Tool icon="back" label="Zurück" onClick={()=>go(back)}/>}<div><h1>{title}</h1>{subtitle&&<small>{subtitle}</small>}</div><div className="header-actions">{children}<Tool icon="help" label="Hilfe & Support" onClick={()=>go('guide')}/></div></header>;}
function Page(){const {page}=useApp();const [section,id]=page.split('?')[0].split('/');if(section==='dashboard')return <Dashboard/>;if(section==='objects')return id?<ObjectDetail id={id}/>:<Objects/>;if(section==='buildings')return <Building id={id}/>;if(section==='assets')return id==='new'?<AssetForm/>:id?<AssetDetail id={id}/>:<Assets/>;return <Workflows section={section} id={id}/>;}
function Dashboard(){const {list,records,go,modal,refresh,offline}=useApp(),[search,S]=useState(''),[hide,H]=useState(localStorage.getItem('hide-welcome')==='1');const objects=list('objects'),assets=list('assets'),ins=list('inspections'),buildings=list('buildings');const steps=[objects.length,buildings.length,assets.length,ins.length],count=steps.filter(Boolean).length;
 const stats=[['Objekte',objects.length],['Prüfungen',ins.length],...['Mängel','Überfällig','Bald fällig','Nicht geprüft','Nicht prüfbar'].map(s=>[s,assets.filter(a=>status(a,records)===s).length])];const results=search?records.filter(r=>['objects','buildings','assets'].includes(r.kind)&&!r.archived&&JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).slice(0,30):[];
 return <><Header title="Dashboard" subtitle={new Date().toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}><Tool icon="refresh" label="Aktualisieren" onClick={refresh}/></Header><div className="content dashboard"><Search value={search} onChange={S} placeholder="Suche nach Objekt, Gebäude, Element…"/>{search?<Card>{results.map(r=><Row key={r.id} title={r.name||r.code} subtitle={r.address||r.location} onClick={()=>go(r.kind+'/'+r.id)}/>)}{!results.length&&<p>Keine Ergebnisse gefunden.</p>}</Card>:<><button className={'offline-card '+(!offline&&buildings.length?'good':'')} onClick={()=>go('settings/offline')}><Icon name={!offline&&buildings.length?'circlecheck':'cloud'}/><span><strong>{buildings.length?`${buildings.length} Gebäude offline-bereit`:'Offline-Modus'}</strong><small>{buildings.length?'Tippe zum Anzeigen':'Tippe auf ein Gebäude, um es offline vorzubereiten.'}</small></span><Icon name="next"/></button>{!hide&&<Card className="welcome"><div className="welcome-title"><Icon name="rocket"/><div><strong>Willkommen bei Augenblick-Control!</strong><small>Einrichtung: {count} von 4</small></div><button className="text-button" onClick={()=>{H(true);localStorage.setItem('hide-welcome','1');}}>Ausblenden</button></div>{['Objekt erstellen','Gebäude hinzufügen','Prüfgegenstände anlegen','Erste Prüfung durchführen'].map((s,i)=><div className="step" key={s}><span className={'step-number '+(steps[i]?'done':'')}>{steps[i]?<Icon name="check"/>:i+1}</span><div>{steps[i]?<s>{s}</s>:<button className="plain" onClick={()=>go(i===0?'objects':i===1?(objects[0]?'objects/'+objects[0].id:'objects'):i===2?'assets/new':'inspections/new')}>{s}</button>}{i===3&&<><small>Dokumentieren Sie Ihre erste Inspektion</small><Button kind="primary" onClick={()=>go('inspections/new')}>Erste Prüfung durchführen</Button></>}</div></div>)}</Card>}<div className="quick-actions"><Row icon="scan" title="Code scannen" subtitle="QR / Strichcode" onClick={()=>modal('scan')} end={<></>}/><Row icon="addbox" title="Neues Element" subtitle="Asset anlegen" onClick={()=>go('assets/new')} end={<></>}/></div><Card className="stats">{stats.map(([s,n])=><button key={s} onClick={()=>go(s==='Objekte'?'objects':'inspections')}><small>{s}</small><strong className={!n?'muted':''}>{n}</strong></button>)}</Card><div className="two-cols"><Card><h3>Objektstatus</h3>{objects.map(o=><Row key={o.id} title={o.name} subtitle={o.address} onClick={()=>go('objects/'+o.id)} end={<Badge>{objectStatus(o,records)}</Badge>}/>)}{!objects.length&&<p>Noch keine Objekte vorhanden.</p>}</Card><Card><h3>Letzte Prüfungen</h3>{ins.slice(-4).reverse().map(i=><Row key={i.id} icon="inspections" title={i.assetSnapshot?.code} subtitle={date(i.date)+' · '+i.result} onClick={()=>go('inspections/'+i.id)}/>)}{!ins.length&&<p className="empty-inline">Keine Prüfungen vorhanden</p>}</Card></div></>}</div></>;
}
function objectStatus(o,records){const ids=records.filter(b=>b.kind==='buildings'&&b.objectId===o.id).map(b=>b.id),assets=records.filter(a=>a.kind==='assets'&&ids.includes(a.buildingId));return assets.some(a=>['Mängel','Überfällig'].includes(status(a,records)))?'Handlungsbedarf':assets.some(a=>status(a,records)==='Nicht geprüft')?'Nicht geprüft':'alles OK';}
export function EditDialog({title,fields,initial={},onSave,onClose}){const [b,S]=useState(initial),[error,E]=useState(''),[busy,B]=useState(false);return <Modal title={title} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();B(true);try{await onSave(b);onClose();}catch(e){E(e.message);}finally{B(false);}}}>{fields.map(({key,...f})=><Field key={key} {...f} value={b[key]??''} onChange={e=>S({...b,[key]:e.target.value})}/>)}<p className="error" role="alert">{error}</p><div className="form-actions"><Button type="button" onClick={onClose}>Abbrechen</Button><Button kind="primary" type="submit" disabled={busy}>{busy?'Speichert…':'Speichern'}</Button></div></form></Modal>;}
export const objectFields=[{key:'name',label:'Name',required:true},{key:'address',label:'Adresse'},{key:'contact',label:'Ansprechpartner'},{key:'email',label:'E-Mail',type:'email'},{key:'phone',label:'Telefon'},{key:'description',label:'Beschreibung',area:true}];
function Objects(){const {list,go,save}=useApp(),[show,S]=useState(false),[q,Q]=useState('');return <><Header title="Objekte"><Button icon="add" onClick={()=>S(true)}>Objekt hinzufügen</Button></Header><div className="content"><Search value={q} onChange={Q} placeholder="Objekt suchen…"/>{list('objects').filter(o=>(o.name+' '+o.address).toLowerCase().includes(q.toLowerCase())).map(o=><Card key={o.id}><Row title={o.name} subtitle={o.address} onClick={()=>go('objects/'+o.id)}/></Card>)}{!list('objects').length&&<Empty title="Noch keine Objekte" description="Legen Sie Ihr erstes Objekt an."><Button icon="add" kind="primary" onClick={()=>S(true)}>Objekt erstellen</Button></Empty>}</div>{show&&<EditDialog title="Neues Objekt" fields={objectFields} onSave={b=>save('objects',b)} onClose={()=>S(false)}/>}</>;}
export function Search({value,onChange,placeholder}){return <div className="search"><Icon name="search"/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>;}
function ObjectDetail({id}){const {find,list,go,save}=useApp(),o=find(id),[dialog,D]=useState('');if(!o)return <Missing/>;const buildings=list('buildings').filter(b=>b.objectId===id);return <><Header title="Objekt Detail" back="objects"><Tool icon="edit" label="Objekt bearbeiten" onClick={()=>D('edit')}/></Header><div className="content"><div className="crumb">Objekte <Icon name="next"/> {o.name}</div><Card><div className="object-title"><Icon name="objects"/><div><h2>{o.name}</h2><p>{o.address}</p></div></div><div className="divider"/><small><Icon name="person"/> {o.contact||'—'}</small></Card><div className="summary-chips"><Badge>{buildings.length} Gebäude</Badge><Badge>{list('inspections').filter(i=>i.objectId===id).length} Prüfungen</Badge></div><Button kind="outline full" icon="reports" onClick={()=>D('pdf')}>PDF-Dateiname konfigurieren</Button><div className="section-heading"><h3>Gebäude</h3><Button icon="add" onClick={()=>D('building')}>Hinzufügen</Button></div>{buildings.map(b=><Card key={b.id}><Row icon="buildings" title={b.name} subtitle={b.address} onClick={()=>go('buildings/'+b.id)}/></Card>)}{!buildings.length&&<Empty title="Keine Gebäude vorhanden" description="Fügen Sie ein Gebäude zu diesem Objekt hinzu."/>}</div>{dialog&&<EditDialog title={dialog==='edit'?'Objekt bearbeiten':dialog==='pdf'?'PDF-Dateiname konfigurieren':'Gebäude hinzufügen'} initial={dialog==='building'?{objectId:id}:o} fields={dialog==='pdf'?[{key:'pdfName',label:'Dateiname (Objekt und Datum werden angehängt)'}]:objectFields} onSave={b=>save(dialog==='building'?'buildings':'objects',b)} onClose={()=>D('')}/>}</>;}
export function Missing(){return <Empty title="Datensatz nicht gefunden" description="Bitte aktualisieren Sie die Ansicht."/>;}
function Building({id}){const {find,list,go,records,save}=useApp(),b=find(id),[tab,T]=useState('Übersicht'),[edit,E]=useState(false);if(!b)return <Missing/>;const assets=list('assets').filter(a=>a.buildingId===id),ins=list('inspections').filter(i=>i.buildingId===id),plans=list('plans').filter(p=>p.buildingId===id);return <><Header title={b.name} back={'objects/'+b.objectId}><Tool icon="edit" label="Gebäude bearbeiten" onClick={()=>E(true)}/></Header><Tabs items={['Übersicht','Grundrisse',`Geräte (${assets.length})`,'Prüfhistorie']} value={tab} onChange={T}/><div className="content"><div className="crumb"><button onClick={()=>go('objects/'+b.objectId)}>{find(b.objectId)?.name}</button><Icon name="next"/>{b.name}</div><div className="quick-actions"><Button icon="add" onClick={()=>go('assets/new?building='+id)}>Element</Button><Button icon="inspections" onClick={()=>go('inspections/new?building='+id)}>Prüfung</Button></div><div className="summary-chips"><Badge>{plans.length} Pläne</Badge><Badge>{assets.length} Geräte</Badge><Badge>{ins.length} Prüfungen</Badge><Badge>{assets.filter(a=>status(a,records)==='Überfällig').length} Überfällig</Badge></div>{tab==='Übersicht'?<><Card><h3>Gebäudeinformationen</h3><dl>{[['Name',b.name],['Adresse',b.address],['Beschreibung',b.description],['Ansprechpartner',b.contact],['Telefon',b.phone]].map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v||'—'}</dd></React.Fragment>)}</dl></Card><Card><h3>Geräte nach Kategorie</h3>{Object.keys(categories).filter(c=>assets.some(a=>a.category===c)).map(c=><div className="bar-row" key={c}><span>{c}</span><progress value={assets.filter(a=>a.category===c).length} max={assets.length}/><span>{assets.filter(a=>a.category===c).length}</span></div>)}</Card><Card><h3>Compliance-Status</h3><Badge>{assets.every(a=>status(a,records)==='Geprüft')&&assets.length?'Geprüft':'Teilweise konform'}</Badge><p>Geprüft ({assets.filter(a=>status(a,records)==='Geprüft').length}) · Offen ({assets.filter(a=>status(a,records)==='Nicht geprüft').length}) · Überfällig ({assets.filter(a=>status(a,records)==='Überfällig').length})</p></Card><Card><h3>Letzte Aktivität</h3><p>{ins.length?date(ins.at(-1).date):'Noch keine Prüfungen durchgeführt'}</p></Card></>:tab==='Grundrisse'?<Workflows section="plans" building={b}/>:tab==='Prüfhistorie'?<InspectionRows rows={ins}/>:<AssetList assets={assets}/>}</div>{edit&&<EditDialog title="Gebäude bearbeiten" initial={b} fields={objectFields} onSave={b=>save('buildings',b)} onClose={()=>E(false)}/>}</>;}
function Assets(){const {list,go}=useApp();return <><Header title="Geräte"><Button icon="add" onClick={()=>go('assets/new')}>Neues Gerät</Button></Header><div className="content"><AssetList assets={list('assets')}/></div></>;}
function AssetList({assets}){const {go,records}=useApp(),[q,Q]=useState(''),[cat,C]=useState('Alle'),[state,S]=useState('Alle');const filtered=assets.filter(a=>(a.code+' '+a.location+' '+JSON.stringify(a.specs)).toLowerCase().includes(q.toLowerCase())&&(cat==='Alle'||a.category===cat)&&(state==='Alle'||status(a,records)===state));return <><Search value={q} onChange={Q} placeholder="Element suchen (Code, Standort…)"/><div className="chips">{['Alle',...Object.keys(categories)].map(c=><button className={cat===c?'selected':''} key={c} onClick={()=>C(c)}>{c}</button>)}</div><div className="chips">{['Alle','Geprüft','Nicht geprüft','Überfällig','Mängel'].map(c=><button className={state===c?'selected':''} key={c} onClick={()=>S(c)}>{c}</button>)}</div><div className="section-heading"><small>{filtered.length} von {assets.length} Gerät(en)</small><Button icon="upload" onClick={()=>go('settings/import')}>Excel hochladen</Button></div>{Object.keys(categories).filter(c=>filtered.some(a=>a.category===c)).map(c=><div key={c}><h3>{categories[c]} ({filtered.filter(a=>a.category===c).length})</h3>{filtered.filter(a=>a.category===c).map(a=><Card key={a.id}><Row icon="assets" title={a.code} subtitle={a.location} end={<Badge>{status(a,records)}</Badge>} onClick={()=>go('assets/'+a.id)}/></Card>)}</div>)}{!filtered.length&&<Empty title="Keine Geräte gefunden" description="Legen Sie ein Gerät an oder ändern Sie die Filter."/>}</>;}
function AssetForm({initial,onDone}){const {list,save,go,find,page}=useApp(),params=new URLSearchParams(page.split('?')[1]);const selectedBuilding=params.get('building')||initial?.buildingId||'';const [b,S]=useState(initial||{buildingId:selectedBuilding,objectId:find(selectedBuilding)?.objectId||'',category:'FLS',code:'',location:'',specs:{}}),[error,E]=useState(''),[busy,B]=useState(false);const field=k=>({value:b[k]||'',onChange:e=>S({...b,[k]:e.target.value})});return <><Header title={initial?'Element bearbeiten':'Neues Element'} back="assets"/><div className="content form-width"><form onSubmit={async e=>{e.preventDefault();B(true);try{const r=await save('assets',b);onDone?onDone():go('assets/'+r.id);}catch(e){E(e.message);}finally{B(false);}}}><Field label="Objekt" required options={list('objects')} value={b.objectId||find(b.buildingId)?.objectId||''} onChange={e=>S({...b,objectId:e.target.value,buildingId:''})}/><Field label="Gebäude" required options={list('buildings').filter(x=>x.objectId===(b.objectId||find(b.buildingId)?.objectId))} {...field('buildingId')}/><Field label="Kategorie" required options={Object.entries(categories).map(([id,name])=>({id,name}))} value={b.category} onChange={e=>S({...b,category:e.target.value,specs:{}})}/><Field label="Objektcode" required {...field('code')}/><Field label="UUID-Code" {...field('uuid')}/><Field label="Standort" required {...field('location')}/>{b.category==='BST'&&<label className="check-label"><input type="checkbox" checked={!!b.fsa} onChange={e=>S({...b,fsa:e.target.checked})}/>Mit Feststellanlage (FSA)</label>}<h3>Stammdaten</h3><p>Optional — werden bei Prüfungen automatisch übernommen</p>{(assetFields[b.category]||[]).map(k=><Field key={k} label={k} value={b.specs?.[k]||''} onChange={e=>S({...b,specs:{...b.specs,[k]:e.target.value}})}/>)}<p role="alert" className="error">{error}</p><Button type="submit" kind="primary full" disabled={busy}>{busy?'Speichert…':initial?'Änderungen speichern':'Element erstellen'}</Button></form></div></>;}
function AssetDetail({id}){const {find,records,go,list}=useApp(),a=find(id),[edit,E]=useState(false);if(!a)return <Missing/>;if(edit)return <AssetForm initial={a} onDone={()=>E(false)}/>;const b=find(a.buildingId);return <><Header title={a.code} back={'buildings/'+a.buildingId}><Tool icon="edit" label="Element bearbeiten" onClick={()=>E(true)}/>{a.fsa&&<Button onClick={()=>go('inspections/new?asset='+id+'&type=monthly')}>Monatsprüfung</Button>}<Button kind="primary" onClick={()=>go('inspections/new?asset='+id)}>Jahreswartung</Button></Header><div className="content"><div className="crumb">{find(b?.objectId)?.name}<Icon name="next"/>{b?.name}<Icon name="next"/>{a.code}</div><Badge>{status(a,records)}</Badge><Card><h3>Geräteinformationen</h3><dl>{[['Kategorie',categories[a.category]],['Standort',a.location],...Object.entries(a.specs||{}),['Nächste Prüfung',date(latest(id,records)?.nextDate)],['Feststellanlage',a.fsa?'Ja':'Nein'],['UUID',a.uuid||a.id]].map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v||'—'}</dd></React.Fragment>)}</dl></Card><Card><h3>Standort</h3><p>{find(b?.objectId)?.name} · {b?.name} · {a.location}</p></Card><h3>Prüfhistorie</h3><InspectionRows rows={list('inspections').filter(i=>i.assetId===id)}/></div></>;}
export function InspectionRows({rows}){const {go}=useApp();return rows.length?rows.slice().reverse().map(i=><Card key={i.id}><Row icon="inspections" title={i.assetSnapshot?.code||'Prüfung'} subtitle={date(i.date)+' · '+(i.inspector||'Offline-Entwurf')} end={<Badge>{i.result}</Badge>} onClick={()=>go('inspections/'+i.id)}/></Card>):<Empty title="Keine Prüfungen vorhanden" description="Hier erscheinen die abgeschlossenen Prüfungen."/>;}
function Scanner({onClose}){const {list,go}=useApp(),[code,S]=useState(''),[error,E]=useState(''),video=useRef(),stream=useRef(),timer=useRef();useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());clearInterval(timer.current);},[]);function findCode(text){const a=list('assets').find(a=>[a.id,a.code,a.uuid].includes(text));if(a){onClose();go('assets/'+a.id);}else E('Kein Gerät zu diesem Code gefunden.');}async function camera(){try{if(!('BarcodeDetector' in window))throw new Error('Kamera-Scan in diesem Browser nicht verfügbar. Bitte Code eingeben.');stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.current.srcObject=stream.current;await video.current.play();const detector=new window.BarcodeDetector();timer.current=setInterval(async()=>{try{const codes=await detector.detect(video.current);if(codes.length){clearInterval(timer.current);findCode(codes[0].rawValue);}}catch{}},500);}catch(e){E(e.message);}}return <Modal title="Code scannen" onClose={onClose}><video ref={video} muted playsInline className="scanner"/><Button icon="photo" onClick={camera}>Kamera starten</Button><Field label="QR / Strichcode" value={code} onChange={e=>S(e.target.value)}/><p className="error">{error}</p><Button kind="primary" onClick={()=>findCode(code.trim())}>Gerät öffnen</Button></Modal>;}
