import React,{useRef,useState} from 'react';
import {Modal,Button,Field} from './App';
export function Signature({signature}){return <svg className="signature-preview" viewBox="0 0 600 240" role="img" aria-label="Gespeicherte Unterschrift">{signature.strokes.map((s,i)=><polyline key={i} points={s.map(([x,y])=>`${x*600},${y*240}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>)}</svg>;}
export function Completion({onClose,onSave,initialResult='Ohne Mängel',allowLater=true}){
 const [step,S]=useState('result'),[result,R]=useState(initialResult),[reason,N]=useState(''),[strokes,T]=useState([]),[busy,B]=useState(false),[error,E]=useState('');const drawing=useRef(false),lines=useRef([]);
 function point(e){const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
 async function submit(extra){B(true);E('');try{await onSave(extra);}catch(e){E(e.message);}finally{B(false);}}
 return <Modal title={step==='signature'?'Unterschrift':step==='reason'?'Prüfung als nicht durchführbar abschließen?':'Ergebnis & Unterschrift'} onClose={busy?()=>{}:onClose}>
 {step==='result'?<div className="completion-options">{[['Ohne Mängel','OK'],['Mit Mängeln','Mangel'],['Schwerwiegende Mängel','Kritisch'],['Nicht prüfbar','Nicht prüfbar']].map(([value,label])=><Button key={value} disabled={busy} onClick={()=>{R(value);S(value==='Nicht prüfbar'?'reason':'signature');}}>{label}</Button>)}{allowLater&&<Button disabled={busy} onClick={()=>submit({completion:'open',signature:null})}>Später entscheiden</Button>}</div>:step==='reason'?<><p>Die Prüfung wird ohne bewertete Prüfpunkte abgeschlossen. Der Grund ist im PDF und Aktivitätsprotokoll sichtbar.</p><Field label="Grund" required area value={reason} onChange={e=>N(e.target.value)}/><Button disabled={busy||!reason.trim()} kind="primary" onClick={()=>submit({completion:'complete',result,nonInspectionReason:reason.trim(),signature:null})}>Prüfung schließen</Button></>:<><p>Bitte unterschreiben Sie im Feld unten.</p><svg viewBox="0 0 600 240" preserveAspectRatio="none" className="signature-pad" aria-label="Unterschriftenfeld" role="img" onPointerDown={e=>{if(busy)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;lines.current=[...lines.current,[point(e)]];T(lines.current);}} onPointerMove={e=>{if(!drawing.current)return;if(lines.current.reduce((n,s)=>n+s.length,0)>=5000)return;const next=lines.current.map((s,i)=>i===lines.current.length-1?[...s,point(e)]:s);lines.current=next;T(next);}} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false}>{strokes.map((s,i)=><polyline key={i} points={s.map(([x,y])=>`${x*600},${y*240}`).join(' ')} fill="none" stroke="#172333" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>)}</svg><div className="form-actions"><Button disabled={busy} onClick={()=>{lines.current=[];T([]);}}>Löschen</Button><Button disabled={busy||!strokes.some(s=>s.length>1)} kind="primary" onClick={()=>submit({completion:'complete',result,signature:{strokes},nonInspectionReason:''})}>{busy?'Speichert…':'Unterschreiben'}</Button></div></>}
 <p className="error" role="alert">{error}</p><Button disabled={busy} onClick={onClose}>Abbrechen</Button></Modal>;
}
