import React,{useState,useEffect,useRef} from 'react';
import {useApp,Modal,Button,Field} from './App';
export function Scanner({onClose,onScan}) {
 const {list,go}=useApp(),[code,S]=useState(''),[error,E]=useState(''),[busy,B]=useState(false),[running,R]=useState(false),video=useRef(),controls=useRef(),alive=useRef(true);
 function stop(){controls.current?.stop();controls.current=null;video.current?.srcObject?.getTracks().forEach(track=>track.stop());R(false);}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controls.current?.stop();video.current?.srcObject?.getTracks().forEach(track=>track.stop());};},[]);
 function accept(text){stop();const value=String(text||'').trim();if(!value)return E('Bitte einen Code eingeben.');if(onScan){onScan(value);onClose();return;}const asset=list('assets').find(a=>[a.id,a.code,a.uuid].includes(value));if(asset){onClose();go('assets/'+asset.id);}else{S(value);E('Kein Gerät zu diesem Code gefunden.');}}
 async function camera(){E('');B(true);try{const {BrowserMultiFormatReader}=await import('@zxing/browser');if(!alive.current)return;const reader=new BrowserMultiFormatReader();const control=await reader.decodeFromConstraints({video:{facingMode:'environment'}},video.current,(result,_error,control)=>{if(result&&alive.current){control.stop();accept(result.getText());}});if(alive.current){controls.current=control;R(true);}else control.stop();}catch(e){if(alive.current)E(e.name==='NotAllowedError'?'Kamerazugriff wurde nicht erlaubt. Sie können einen Code aus einem Bild lesen oder manuell eingeben.':e.message);}finally{if(alive.current)B(false);}}
 async function picture(file){if(!file)return;if(file.size>10485760)return E('Maximal 10 MB pro Bild.');E('');B(true);const url=URL.createObjectURL(file);try{const {BrowserMultiFormatReader}=await import('@zxing/browser');const result=await new BrowserMultiFormatReader().decodeFromImageUrl(url);if(alive.current)accept(result.getText());}catch{if(alive.current)E('Kein lesbarer QR- oder Strichcode im Bild gefunden.');}finally{URL.revokeObjectURL(url);if(alive.current)B(false);}}
 return <Modal title="Code scannen" onClose={()=>{stop();onClose();}}><video ref={video} muted playsInline className="scanner"/>{running?<Button onClick={stop}>Kamera stoppen</Button>:<Button disabled={busy} onClick={camera}>Kamera starten</Button>}<label className="button">Code aus Bild lesen<input className="file-input" type="file" accept="image/*" disabled={busy} onChange={e=>picture(e.target.files[0])}/></label><Field label="QR / Strichcode" value={code} onChange={e=>S(e.target.value)}/><p className="error" role="alert">{error}</p><Button kind="primary" disabled={busy} onClick={()=>accept(code)}>{onScan?'Code übernehmen':'Gerät öffnen'}</Button></Modal>;
}
