import React,{useEffect,useState} from 'react';
import {useApp,Header,Card,Row,Button,Field,Modal} from './App';
import {request,post} from './data';
export function Workspaces(){
 const {user,queue,notify}=useApp(),[rows,R]=useState([]),[mode,M]=useState(''),[value,V]=useState(''),[busy,B]=useState(false),[error,E]=useState('');
 useEffect(()=>{request('/workspaces').then(r=>R(r.workspaces)).catch(e=>E(e.message));},[]);
 async function choose(id){if(queue.length)return notify('Bitte ausstehende Prüfungen zuerst synchronisieren.');B(true);try{await request('/auth/me',{headers:{'X-Workspace':id}});sessionStorage.setItem('augenblick-workspace',id);location.hash='/dashboard';location.reload();}catch(e){E(e.message);B(false);}}
 async function submit(e){e.preventDefault();E('');B(true);try{const r=await post(mode==='create'?'/workspaces':'/workspaces/redeem',mode==='create'?{name:value}:{token:value});await choose(r.workspaceId);}catch(e){E(e.message);}finally{B(false);}}
 return <><Header title="Arbeitsbereiche" back="settings"/><div className="content form-width"><p>Jeder Arbeitsbereich hat eigene Gebäude, Prüfungen, Dateien und Mitglieder. Ihre Zugriffsrechte gelten jeweils nur dort.</p>{rows.map(w=><Card key={w.id}><Row title={w.name} subtitle={(w.external?'Externer Zugang · ':'')+({admin:'Admin',lead:'Teamleiter',inspector:'Prüfer'}[w.role])+(w.id===user.workspaceId?' · Aktiv':'')} onClick={()=>!busy&&choose(w.id)}/></Card>)}<div className="form-actions"><Button disabled={busy||!!queue.length} onClick={()=>{V('');M('redeem');}}>Zugangsschlüssel einlösen</Button><Button disabled={busy||!!queue.length} onClick={()=>{V('');M('create');}}>Arbeitsbereich erstellen</Button></div><p className="error" role="alert">{error}</p></div>{mode&&<Modal title={mode==='create'?'Arbeitsbereich erstellen':'Zugangsschlüssel einlösen'} onClose={()=>!busy&&M('')}><form onSubmit={submit}><Field required label={mode==='create'?'Firmenname':'Zugangsschlüssel oder Einladungslink'} value={value} onChange={e=>V(e.target.value)}/><p className="error" role="alert">{error}</p><Button type="submit" kind="primary" disabled={busy}>{busy?'Bitte warten…':mode==='create'?'Erstellen':'Einlösen'}</Button></form></Modal>}</>;
}
